# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/index.html

In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::StridedArray{T, 2}) where T in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1207
[2] factorize(A::Adjoint) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1283
[3] factorize(A::Transpose) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1284
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\triangular.jl:2676
[5] factorize(A::Union{Hermitian{Complex{Float64},var"#s828"}, Hermitian{Float64,var"#s828"}, Symmetric{Float64,var"#s828"}} where var"#s828"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1538
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\symmetric.jl:634
[7] factorize(A::Tridiagonal) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\lu.jl:555
[8] factorize(D::Diagonal) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\bidiag.jl:875
[10] factorize(S::SymTridiagonal) in LinearAlgebra at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\ldlt.jl:166
[11] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\TadeuszSatlawa\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1508

In [3]:
# wiersze vs kolumny
x1 = [1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [4]:
y1 = [1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [6]:
# iloczyn skalarny
dot(x1, y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [7]:
# losujemy macierz 3x3
A = rand(3,3)

3×3 Array{Float64,2}:
 0.426808  0.87078   0.744177
 0.116261  0.861701  0.454764
 0.515208  0.434804  0.731423

In [8]:
# losujemy wektor x
x = rand(3)

3-element Array{Float64,1}:
 0.8820355543540461
 0.4044150789954668
 0.7235163896359369

In [9]:
# wyliczamy b
b = A*x

3-element Array{Float64,1}:
 1.2670410920157829
 0.7800602545631814
 1.1594692797627135

### Sposoby rozwiązania Ax=b

In [10]:
# mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.8820355543540419
 0.4044150789954646
 0.7235163896359431

In [11]:
# najlepiej używać zoptymalizowanego operatora "\""
x = A\b

3-element Array{Float64,1}:
 0.8820355543540427
 0.40441507899546547
 0.7235163896359402

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [12]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af = factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.225658  1.0       0.0
 0.828419  0.668663  1.0
U factor:
3×3 Array{Float64,2}:
 0.515208  0.434804   0.731423
 0.0       0.763584   0.289713
 0.0       0.0       -0.0554673

In [13]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.225658  1.0       0.0
 0.828419  0.668663  1.0

In [14]:
# Macierz U
Af.U

3×3 Array{Float64,2}:
 0.515208  0.434804   0.731423
 0.0       0.763584   0.289713
 0.0       0.0       -0.0554673

In [15]:
# wektor permutacji wierszy 
Af.p

3-element Array{Int64,1}:
 3
 2
 1

In [16]:
# sprawdzenie czy dostaniemy pierwotna macierz
Af.P * A - Af.L*Af.U

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [17]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A = factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.225658  1.0       0.0
 0.828419  0.668663  1.0
U factor:
3×3 Array{Float64,2}:
 0.515208  0.434804   0.731423
 0.0       0.763584   0.289713
 0.0       0.0       -0.0554673

In [18]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.8820355543540427
 0.40441507899546547
 0.7235163896359402

In [19]:
# dla różnych prawych stron równania z tą samą macierzą
c = rand(3);
A\c

3-element Array{Float64,1}:
  8.146754007861663
  4.109285185656289
 -8.14676332319351

### Faktoryzacja QR


In [20]:
B = rand(10, 5)

10×5 Array{Float64,2}:
 0.527932   0.545465   0.953677   0.657313   0.209823
 0.215046   0.157795   0.478875   0.0743982  0.868885
 0.0532183  0.203356   0.796062   0.0650214  0.75715
 0.244892   0.247211   0.912153   0.186526   0.231066
 0.920043   0.0562453  0.814678   0.233052   0.00247366
 0.240763   0.860322   0.112277   0.820414   0.979739
 0.870474   0.275154   0.932202   0.203896   0.613602
 0.473385   0.0151019  0.0736561  0.424002   0.980705
 0.461177   0.586773   0.330404   0.255356   0.313383
 0.724831   0.313144   0.125675   0.501665   0.745885

In [21]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
qrf = factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.100276     0.486044     0.00102614  …  -0.0826574  -0.0156237  -0.0988664
 -0.415246     0.00343135  -0.241036       -0.561658   -0.134926   -0.409364
 -0.361847     0.222294    -0.523406        0.473486   -0.239155    0.436671
 -0.110428     0.455307    -0.259913       -0.2658      0.58175     0.139082
 -0.00118218   0.470912     0.502255        0.171345   -0.351022   -0.122647
 -0.468223    -0.243762    -0.0671429   …   0.0341807  -0.322248   -0.13596
 -0.293244     0.346358     0.242962       -0.0106217  -0.120531   -0.106898
 -0.468685    -0.266427     0.177756        0.364325    0.406597   -0.275044
 -0.149768     0.0925372    0.210537        0.297835    0.421566   -0.109391
 -0.356463    -0.162305     0.456805       -0.36165     0.0359966   0.692857
R factor:
5×5 Array{Float64,2}:
 -2.09246  -1.13896  -1.10693   -0.911262   -1.00093
  0.0       1.72714   0.855642   0.334948 

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

In [22]:
# sprawdzenie macierzy Q
transpose(qrf.Q)*qrf.Q

10×10 Array{Float64,2}:
  1.0           4.16334e-17  -5.55112e-17  …   6.245e-17     0.0
  4.16334e-17   1.0          -1.38778e-16      2.77556e-17  -8.32667e-17
 -5.55112e-17  -1.38778e-16   1.0             -4.85723e-17  -1.11022e-16
 -5.38848e-17  -6.4239e-17   -9.56266e-17      1.12242e-16  -7.15573e-17
  1.12757e-16  -1.04951e-16  -1.31839e-16     -1.29671e-16  -4.85723e-17
 -6.93889e-17   3.81639e-17   4.16334e-17  …   2.77556e-17   0.0
 -2.77556e-17   8.67362e-18   9.71445e-17     -2.60209e-17  -9.71445e-17
 -1.11022e-16   1.249e-16     2.77556e-17      1.14492e-16   0.0
  6.245e-17     2.77556e-17  -4.85723e-17      1.0           3.46945e-18
  0.0          -8.32667e-17  -1.11022e-16      3.46945e-18   1.0

In [23]:
isapprox(transpose(qrf.Q)*qrf.Q, I)

true

In [24]:
qrf.R

5×5 Array{Float64,2}:
 -2.09246  -1.13896  -1.10693   -0.911262   -1.00093
  0.0       1.72714   0.855642   0.334948    0.228743
  0.0       0.0       1.02697    0.0984391   0.370028
  0.0       0.0       0.0        0.856876    0.575146
  0.0       0.0       0.0        0.0         0.469404

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [25]:
A = zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [26]:
x=[1; 2; 3; 4; 5; 6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [27]:
A[:,1] = x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [28]:
A[:,2] = x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [29]:
A[:,3] = ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [30]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [31]:
AF = factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [32]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           1.11022e-16  …   8.32667e-17   0.0
  0.0           1.0           9.71445e-17     -5.55112e-17  -1.249e-16
  1.11022e-16   9.71445e-17   1.0             -4.16334e-17   0.0
 -9.71445e-17   3.46945e-17   2.60209e-17     -9.88792e-17  -2.08167e-17
  8.32667e-17  -5.55112e-17  -4.16334e-17      1.0           0.0
  0.0          -1.249e-16     0.0          …   0.0           1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [33]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285725
  3.9428571428571515
 -2.8000000000000163

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [34]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285726
  3.942857142857151
 -2.8000000000000145

In [35]:
# sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
fit(x,y, 2)

Polynomial(-2.8 + 3.9428571428571417*x - 0.5714285714285711*x^2)

In [36]:
@which fit

Polynomials

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/master/src/common.jl#L142">
fit</a>  z pakietu Polynomials używa własnie tej metody


### Zadania

#### Zadanie 1 (1pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254




# Zadanie 1


In [2]:
x = rand(1000)

1000-element Array{Float64,1}:
 0.02873531678644281
 0.17878932527165414
 0.43920741248075834
 0.16781233781504512
 0.35704673249315877
 0.06764394155967457
 0.3845596809167837
 0.4281643751896853
 0.23594226298879595
 0.21265088712748037
 0.8134097371056099
 0.2975341754723737
 0.8081546417293832
 ⋮
 0.3949407151179749
 0.11512223151319279
 0.9360805543946229
 0.4292495555320144
 0.7819461920107287
 0.5567872811478214
 0.061983507131893045
 0.2147000687762164
 0.6931951765766826
 0.08412198590832509
 0.818483894117676
 0.6562362823923487

In [3]:
A = rand(1000,1000)

1000×1000 Array{Float64,2}:
 0.181968   0.243417   0.564827   …  0.946917  0.548422   0.576005
 0.892764   0.416575   0.920988      0.836842  0.246884   0.996058
 0.92438    0.7496     0.323851      0.675069  0.398826   0.302901
 0.0348572  0.270153   0.464207      0.630177  0.769529   0.375465
 0.325619   0.196901   0.277644      0.531458  0.282947   0.326796
 0.976714   0.722402   0.766368   …  0.651291  0.53185    0.03728
 0.288807   0.850341   0.83519       0.119738  0.763848   0.382343
 0.79119    0.784428   0.384667      0.301243  0.791511   0.953877
 0.508909   0.162818   0.314299      0.293969  0.0651354  0.994902
 0.399933   0.0111849  0.0546137     0.708298  0.275189   0.416359
 0.643604   0.857695   0.0489328  …  0.712795  0.0202004  0.326943
 0.690092   0.0362815  0.011996      0.898158  0.718939   0.239266
 0.843742   0.349534   0.252425      0.81286   0.961962   0.0691796
 ⋮                                ⋱                       
 0.739317   0.216464   0.359247      0.414

In [4]:
b = A*x

1000-element Array{Float64,1}:
 250.16963382133844
 247.78566117240445
 252.64226378133375
 254.96451083571742
 248.12808331684815
 253.60439153380003
 249.49119830528102
 242.67513325341127
 238.61295530062955
 247.1487776580648
 260.6010050271384
 246.45838937054296
 253.60491195720675
   ⋮
 260.8574923293116
 243.64168191966027
 254.80034158577698
 252.9750886981187
 253.0932602780477
 250.96373068119965
 247.37493909055578
 247.17905231249844
 247.0825489241583
 244.49248201299145
 254.45829243554417
 255.86138210304634

In [19]:
values = [inv(A) * b,A\b,factorize(A)\b]

  0.015469 seconds (5 allocations: 7.645 MiB)
  0.031148 seconds (104 allocations: 15.293 MiB)
  0.072111 seconds (212 allocations: 23.431 MiB)


1-element Array{Tuple{Array{Float64,1},Tuple{Array{Float64,1},Array{Float64,1}}},1}:
 ([0.028735316787006582, 0.1787893252659103, 0.4392074124806129, 0.16781233781823346, 0.35704673249625785, 0.0676439415593535, 0.3845596809147196, 0.4281643751906472, 0.2359422629891199, 0.2126508871277828  …  0.9360805543936976, 0.42924955553119304, 0.7819461920113291, 0.5567872811474199, 0.06198350713242462, 0.21470006877626702, 0.6931951765753723, 0.08412198590887954, 0.8184838941159249, 0.6562362823918466], ([0.02873531678776399, 0.17878932526996572, 0.439207412481014, 0.1678123378165385, 0.35704673249344326, 0.06764394155944727, 0.38455968091851617, 0.4281643751893478, 0.2359422629886036, 0.21265088712786046  …  0.9360805543960458, 0.4292495555320157, 0.7819461920110619, 0.5567872811476393, 0.061983507131857726, 0.2147000687757044, 0.6931951765763134, 0.08412198590888566, 0.8184838941169279, 0.6562362823923673], [0.02873531678776399, 0.17878932526996572, 0.439207412481014, 0.1678123378165385, 0.35

In [29]:
firstime = @time inv(A) * b

  0.068613 seconds (6 allocations: 8.133 MiB)


1000-element Array{Float64,1}:
 0.028735316787006582
 0.1787893252659103
 0.4392074124806129
 0.16781233781823346
 0.35704673249625785
 0.0676439415593535
 0.3845596809147196
 0.4281643751906472
 0.2359422629891199
 0.2126508871277828
 0.8134097371054025
 0.29753417547127015
 0.8081546417295868
 ⋮
 0.3949407151186861
 0.11512223151126477
 0.9360805543936976
 0.42924955553119304
 0.7819461920113291
 0.5567872811474199
 0.06198350713242462
 0.21470006877626702
 0.6931951765753723
 0.08412198590887954
 0.8184838941159249
 0.6562362823918466

In [30]:
secondtime = @time A\b

  0.039513 seconds (4 allocations: 7.645 MiB, 22.00% gc time)


1000-element Array{Float64,1}:
 0.02873531678776399
 0.17878932526996572
 0.439207412481014
 0.1678123378165385
 0.35704673249344326
 0.06764394155944727
 0.38455968091851617
 0.4281643751893478
 0.2359422629886036
 0.21265088712786046
 0.8134097371049949
 0.29753417547073074
 0.8081546417303288
 ⋮
 0.39494071511835777
 0.1151222315123564
 0.9360805543960458
 0.4292495555320157
 0.7819461920110619
 0.5567872811476393
 0.061983507131857726
 0.2147000687757044
 0.6931951765763134
 0.08412198590888566
 0.8184838941169279
 0.6562362823923673

In [31]:
thirdtime = @time factorize(A)\b

  0.029077 seconds (5 allocations: 7.645 MiB)


1000-element Array{Float64,1}:
 0.02873531678776399
 0.17878932526996572
 0.439207412481014
 0.1678123378165385
 0.35704673249344326
 0.06764394155944727
 0.38455968091851617
 0.4281643751893478
 0.2359422629886036
 0.21265088712786046
 0.8134097371049949
 0.29753417547073074
 0.8081546417303288
 ⋮
 0.39494071511835777
 0.1151222315123564
 0.9360805543960458
 0.4292495555320157
 0.7819461920110619
 0.5567872811476393
 0.061983507131857726
 0.2147000687757044
 0.6931951765763134
 0.08412198590888566
 0.8184838941169279
 0.6562362823923673

In [32]:
times = [firstime,secondtime,thirdtime]

3-element Array{Array{Float64,1},1}:
 [0.028735316787006582, 0.1787893252659103, 0.4392074124806129, 0.16781233781823346, 0.35704673249625785, 0.0676439415593535, 0.3845596809147196, 0.4281643751906472, 0.2359422629891199, 0.2126508871277828  …  0.9360805543936976, 0.42924955553119304, 0.7819461920113291, 0.5567872811474199, 0.06198350713242462, 0.21470006877626702, 0.6931951765753723, 0.08412198590887954, 0.8184838941159249, 0.6562362823918466]
 [0.02873531678776399, 0.17878932526996572, 0.439207412481014, 0.1678123378165385, 0.35704673249344326, 0.06764394155944727, 0.38455968091851617, 0.4281643751893478, 0.2359422629886036, 0.21265088712786046  …  0.9360805543960458, 0.4292495555320157, 0.7819461920110619, 0.5567872811476393, 0.061983507131857726, 0.2147000687757044, 0.6931951765763134, 0.08412198590888566, 0.8184838941169279, 0.6562362823923673]
 [0.02873531678776399, 0.17878932526996572, 0.439207412481014, 0.1678123378165385, 0.35704673249344326, 0.06764394155944727, 0.3845596809

In [34]:
errorvalues = [sqrt(dot(values[1],x)),sqrt(dot(values[2],x)),sqrt(dot(values[3],x))]

3-element Array{Float64,1}:
 18.382432997228815
 18.38243299722869
 18.38243299722869

# Zadanie 2


In [46]:
xs = 0:10
ys = map(exp, xs)

11-element Array{Float64,1}:
     1.0
     2.718281828459045
     7.38905609893065
    20.085536923187668
    54.598150033144236
   148.4131591025766
   403.4287934927351
  1096.6331584284585
  2980.9579870417283
  8103.083927575384
 22026.465794806718

In [64]:
A = zeros(11,3)
A[:,1] = xs.^2
A[:,3] = ones(11)
A[:,2] = xs

0:10

In [65]:
A

11×3 Array{Float64,2}:
   0.0   0.0  1.0
   1.0   1.0  1.0
   4.0   2.0  1.0
   9.0   3.0  1.0
  16.0   4.0  1.0
  25.0   5.0  1.0
  36.0   6.0  1.0
  49.0   7.0  1.0
  64.0   8.0  1.0
  81.0   9.0  1.0
 100.0  10.0  1.0

In [66]:
Afactorized = factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
11×11 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
  0.0          3.88578e-16  -0.761853   …  -0.126755   -0.305093   -0.533412
 -0.00628285  -0.180555     -0.495663      -0.0076019   0.185417    0.418096
 -0.0251314   -0.312143     -0.275368       0.414472    0.353916    0.24599
 -0.0565456   -0.394764     -0.100968      -0.0490099   0.0159554   0.0968077
 -0.100526    -0.428418      0.0275368     -0.120319   -0.0408803   0.0622431
 -0.157071    -0.413105      0.110147   …  -0.171831   -0.0936174   0.0109406
 -0.226183    -0.348824      0.146863      -0.203546   -0.142256   -0.0571
 -0.30786     -0.235576      0.137684      -0.215465   -0.186796   -0.141879
 -0.402102    -0.0733617     0.0826105      0.792412   -0.227238   -0.243395
 -0.508911     0.13782      -0.0183579     -0.179913    0.736419   -0.361649
 -0.628285     0.397969     -0.165221   …  -0.132443   -0.295826    0.503358
R factor:
3×3 Array{Float64,2}:
 -159.163  -19.005

In [67]:
A\ys

3-element Array{Float64,1}:
   423.9531082523477
 -2839.9726803751155
  2529.2113262553435

In [60]:
using Polynomials

In [69]:
fit(xs,ys,2)

Polynomial(2529.211326255355 - 2839.97268037512*x + 423.95310825234816*x^2)

# Zadanie 3 - uzycie faktoryzacji QR do znajdowania wartości własnych

Faktoryzacja QR może zostać użyta do znalezienia wartości w następujący sposób. Mając daną macierz A i chcąc znaleść jej wartości własne możemy użyć gotowej faktoryzacji QR w Julii. 

In [108]:
T = rand(5, 5)

5×5 Array{Float64,2}:
 0.964156  0.777062  0.334724   0.632129  0.233707
 0.747619  0.381129  0.195553   0.394296  0.560621
 0.167855  0.864053  0.710867   0.117321  0.279427
 0.904667  0.14736   0.0195358  0.673353  0.0882015
 0.360884  0.242801  0.993985   0.91599   0.221336

In [109]:
qr(T)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.614054   0.259663    0.270974   -0.526381    0.45278
 -0.476145  -0.0491658   0.0713102   0.823217    0.296811
 -0.106904   0.869747   -0.0119531   0.1555     -0.455839
 -0.576167  -0.414565    0.0371125  -0.110776   -0.694636
 -0.229841   0.0428235  -0.95915    -0.0937303   0.128787
R factor:
5×5 Array{Float64,2}:
 -1.57015  -0.891711  -0.614359  -1.18694     -0.542009
  0.0       0.883851   0.730043   0.00687082   0.249066
  0.0       0.0       -0.856506  -0.655576    -0.109054
  0.0       0.0        0.0       -0.150353     0.351428
  0.0       0.0        0.0        0.0          0.11208

Uzywajac funkcji qr otrzymujemy faktoryzację otrzymanej macierzy (w szczególności dwie macierze Q i R), dzięki którym możemy znaleść wartości własne macierzy wyjściowej. Chcąc znaleść wartości własne macierzy wejściowej nadpisujemy macierz przez macierz otrzymana poprzez mnożenie dwóch macierzy R i Q. Proces ten powtarzamy dla ilości iteracji ile chcemy. Im większa ilość iteracji, tym bardziej można zauważyć wartości własne. 

Dodatkowo z każdą kolejną iteracją, otrzymywana macierz staje się coraz bardziej macierzą trójkątną.

Poniżej znajduje się przykładowe znajdywanie wartości własnych dla macierzy T o wymiarach 5x5 gdzie ilość iteracji jest równa 20.

In [119]:
for i in 1:20
    backup = qr(T)
    T = backup.R * backup.Q
end

In [120]:
T

5×5 Array{Float64,2}:
  2.40572       0.327809      0.41576      -0.144567     -0.331387
 -4.00006e-10   0.789753     -0.0642282    -0.430346      0.461382
  1.2211e-15   -1.89017e-6    0.014877      0.481915      0.644826
 -6.31887e-17   2.9296e-7    -0.349154     -0.195754      0.117157
 -4.30541e-32  -5.26714e-24  -7.73347e-17  -2.68231e-17  -0.0637602

In [2]:
A = rand(10,10) #Oryginalna macierz

10×10 Array{Float64,2}:
 0.0899699  0.70299   0.961648  0.0554382  …  0.449494  0.215509   0.00436191
 0.777592   0.642062  0.783826  0.676708      0.295891  0.0315888  0.30293
 0.760369   0.931289  0.127395  0.807179      0.893632  0.742384   0.0836986
 0.0484705  0.369918  0.421714  0.0525808     0.76675   0.362636   0.258707
 0.437613   0.488409  0.144483  0.245601      0.740358  0.557901   0.330268
 0.915983   0.854446  0.93605   0.927451   …  0.153754  0.357014   0.264353
 0.166636   0.817109  0.954856  0.67506       0.871647  0.36309    0.808713
 0.479954   0.930066  0.48088   0.544811      0.219386  0.800652   0.524857
 0.700383   0.676289  0.873973  0.066552      0.244676  0.12704    0.308455
 0.241459   0.881882  0.171035  0.972511      0.334393  0.650249   0.403354

In [10]:
values = Matrix{Float64}[]
for i in 1:30
    backup = qr(A)
    A = backup.R * backup.Q
    if(i%5 == 0)
        push!(values,A)
    end
end

In [13]:
values[1] #Macierz po wykonaniu 5 iteracji algorytmu

10×10 Array{Float64,2}:
  4.587          0.796607       0.313286      …  -0.762306     -0.405797
  2.19201e-65   -0.788211       0.385764          0.29209      -0.0139045
 -1.95407e-66   -0.71017       -0.975109          0.0594706     0.0806248
 -1.51556e-72   -2.57557e-8    -8.31748e-8       -0.00839473   -0.0846189
  4.17315e-75    7.39094e-8    -6.04535e-8        0.184287     -0.355663
 -4.34469e-88   -2.15124e-21    1.85126e-21   …  -0.0929686    -0.112025
 -6.43222e-97   -2.58799e-31    2.44588e-31      -0.0412285    -0.182367
 -4.15874e-101  -1.40557e-35    1.53524e-35       0.490877     -0.160243
 -3.11403e-102  -3.37562e-36    3.55093e-36       0.397085     -0.200899
  1.77708e-190   1.82629e-124  -1.92266e-124     -2.49382e-89  -0.0556345

In [15]:
values[3]#Macierz po wykonaniu 15 iteracji algorytmu

10×10 Array{Float64,2}:
  4.587          0.141694       0.844189      …   0.196199     -0.405797
  8.84901e-72   -0.782333       0.706639         -0.0494237    -0.0762721
 -4.32104e-73   -0.389295      -0.980986          0.434898      0.0296018
  8.12688e-80    4.41905e-10    2.46465e-8       -0.338463     -0.187202
 -1.82605e-82   -8.01705e-9     1.18414e-8       -0.077907      0.314026
 -7.47076e-97   -9.16982e-24    1.4257e-23    …  -0.154038     -0.112025
 -1.30521e-106  -1.30182e-34    2.22478e-34      -0.0153096    -0.182382
 -2.32317e-111  -1.59991e-39    3.20079e-39       0.388472     -0.209092
 -2.40159e-112  -6.45351e-40    1.22868e-39       0.0293009     0.149377
  1.22422e-209   3.11883e-137  -5.94264e-137     -4.51622e-99  -0.0556345

In [17]:
values[6] #Macierz po wykonaniu 30 iteracji algorytmu

10×10 Array{Float64,2}:
  4.587          0.747818      -0.416533      …  -0.0294544      0.405797
 -1.11547e-81   -1.0589         0.487718         -0.460688      -0.053461
  8.81586e-83   -0.608216      -0.704423          0.135426      -0.0619324
 -6.82156e-91    4.62943e-11    9.75956e-10      -0.0503587      0.340936
  2.47588e-93   -8.32407e-10    1.16545e-9        0.311746       0.131984
  5.32688e-110  -5.00693e-27    7.25934e-27   …   0.168433       0.112025
 -3.77278e-121   2.8816e-39    -4.46233e-39       0.0234506      0.182385
 -1.43719e-126   7.57658e-45   -1.31472e-44       0.468694      -0.235778
 -1.23303e-127   2.53732e-45   -4.24574e-45       0.0287202      0.102178
  2.21356e-238  -4.31842e-156   7.23028e-156     -1.58061e-112  -0.0556345